
package cn.tsa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CertAPI", targetNamespace = "http://webservice.certapi.tsa.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CertAPI {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.tsa.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handle", targetNamespace = "http://webservice.certapi.tsa.cn/", className = "cn.tsa.Handle")
    @ResponseWrapper(localName = "handleResponse", targetNamespace = "http://webservice.certapi.tsa.cn/", className = "cn.tsa.HandleResponse")
    @Action(input = "http://webservice.certapi.tsa.cn/CertAPI/handleRequest", output = "http://webservice.certapi.tsa.cn/CertAPI/handleResponse")
    public Result handle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
