
package cn.tsa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CertAPIService", targetNamespace = "http://webservice.certapi.tsa.cn/", wsdlLocation = "http://ra.1sign.cn:8080/service/CertAPI?wsdl")
public class CertAPIService
    extends Service
{

//    private final static URL CERTAPISERVICE_WSDL_LOCATION;
//    private final static WebServiceException CERTAPISERVICE_EXCEPTION;
    private final static QName CERTAPISERVICE_QNAME = new QName("http://webservice.certapi.tsa.cn/", "CertAPIService");

    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://ra.1sign.cn:8080/service/CertAPI?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        CERTAPISERVICE_WSDL_LOCATION = url;
//        CERTAPISERVICE_EXCEPTION = e;
    }

//    public CertAPIService() {
//        super(__getWsdlLocation(), CERTAPISERVICE_QNAME);
//    }
//
//    public CertAPIService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), CERTAPISERVICE_QNAME, features);
//    }

    public CertAPIService(URL wsdlLocation) {
        super(wsdlLocation, CERTAPISERVICE_QNAME);
    }

//    public CertAPIService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, CERTAPISERVICE_QNAME, features);
//    }

    public CertAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public CertAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns CertAPI
     */
    @WebEndpoint(name = "CertAPIPort")
    public CertAPI getCertAPIPort() {
        return super.getPort(new QName("http://webservice.certapi.tsa.cn/", "CertAPIPort"), CertAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CertAPI
     */
    @WebEndpoint(name = "CertAPIPort")
    public CertAPI getCertAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.certapi.tsa.cn/", "CertAPIPort"), CertAPI.class, features);
    }

//    private static URL __getWsdlLocation() {
//        if (CERTAPISERVICE_EXCEPTION!= null) {
//            throw CERTAPISERVICE_EXCEPTION;
//        }
//        return CERTAPISERVICE_WSDL_LOCATION;
//    }

}
