
package cn.tsa.certapi.webservice.cfca;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CfcaCertAPIService", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/", wsdlLocation = "http://192.168.50.172:18088/service/CfcaCertAPI?wsdl")
public class CfcaCertAPIService
    extends Service
{

    private final static URL CFCACERTAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException CFCACERTAPISERVICE_EXCEPTION;
    private final static QName CFCACERTAPISERVICE_QNAME = new QName("http://cfca.webservice.certapi.tsa.cn/", "CfcaCertAPIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.50.172:18088/service/CfcaCertAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CFCACERTAPISERVICE_WSDL_LOCATION = url;
        CFCACERTAPISERVICE_EXCEPTION = e;
    }

    public CfcaCertAPIService() {
        super(__getWsdlLocation(), CFCACERTAPISERVICE_QNAME);
    }

    public CfcaCertAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CFCACERTAPISERVICE_QNAME, features);
    }

    public CfcaCertAPIService(URL wsdlLocation) {
        super(wsdlLocation, CFCACERTAPISERVICE_QNAME);
    }

    public CfcaCertAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CFCACERTAPISERVICE_QNAME, features);
    }

    public CfcaCertAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CfcaCertAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CfcaCertAPI
     */
    @WebEndpoint(name = "CfcaCertAPIPort")
    public CfcaCertAPI getCfcaCertAPIPort() {
        return super.getPort(new QName("http://cfca.webservice.certapi.tsa.cn/", "CfcaCertAPIPort"), CfcaCertAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CfcaCertAPI
     */
    @WebEndpoint(name = "CfcaCertAPIPort")
    public CfcaCertAPI getCfcaCertAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cfca.webservice.certapi.tsa.cn/", "CfcaCertAPIPort"), CfcaCertAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CFCACERTAPISERVICE_EXCEPTION!= null) {
            throw CFCACERTAPISERVICE_EXCEPTION;
        }
        return CFCACERTAPISERVICE_WSDL_LOCATION;
    }

}
