
package cn.tsa.certapi.webservice.cfca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CfcaCertAPI", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CfcaCertAPI {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCfcaCertAPIService", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/", className = "cn.tsa.certapi.webservice.cfca.SetCfcaCertAPIService")
    @ResponseWrapper(localName = "setCfcaCertAPIServiceResponse", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/", className = "cn.tsa.certapi.webservice.cfca.SetCfcaCertAPIServiceResponse")
    @Action(input = "http://cfca.webservice.certapi.tsa.cn/CfcaCertAPI/setCfcaCertAPIServiceRequest", output = "http://cfca.webservice.certapi.tsa.cn/CfcaCertAPI/setCfcaCertAPIServiceResponse")
    public void setCfcaCertAPIService(
        @WebParam(name = "arg0", targetNamespace = "")
        CfcaCertWebServiceImpl arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.tsa.certapi.webservice.cfca.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handle", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/", className = "cn.tsa.certapi.webservice.cfca.Handle")
    @ResponseWrapper(localName = "handleResponse", targetNamespace = "http://cfca.webservice.certapi.tsa.cn/", className = "cn.tsa.certapi.webservice.cfca.HandleResponse")
    @Action(input = "http://cfca.webservice.certapi.tsa.cn/CfcaCertAPI/handleRequest", output = "http://cfca.webservice.certapi.tsa.cn/CfcaCertAPI/handleResponse")
    public Result handle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
